name: Integración continua para el segundo proyecto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Correr pruebas unitarias, dar formato y ejecutar clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Instalar toolchain de Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Caché de dependencias
        uses: Swatinem/rust-cache@v2

      - name: Verificar formato
        run: cargo fmt --all -- --check

      - name: Ejecutar clippy
        run: cargo clippy --workspace --all-targets --all-features

      - name: Ejecutar pruebas unitarias
        run: cargo test --workspace --all-targets

      - name: check
        run: cargo check --workspace --all-targets

      - name: Compilar
        run: cargo build --workspace --all-targets